### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by bunsung92** [nhn-on7/marketgg-shop#123]
## Overview
1. 회원가입

## To-do

- [x] 추천인 체크 로직 추가
- [x] 추천인 과 가입하는 회원 적립금 추가
- [x] 회원 배송지 로직 추가
- [x] JavaDoc 추가
