### ISSUE TITLE
RE: [ES] Server [Shop] Server 연동 및 설정

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-shop#140]
## Overview

1. [ES] Server 와 Market GG Shop 의 서버의 연동과 Repository 연결을 위해 설정을 해줍니다.

## To-do

- [ ] pox.xml 에 elasticsearch 의존성 추가
- [ ] yml 에 Spring.elastic data 추가
- [ ] repository 연동 및 기존 Jpa Repository 와 충돌 방지 Marker Interface 생성
