### ISSUE TITLE
1:1 문의 추가 기능 구현

### ISSUE THREAD

**Issue by Jungmin-Kim228** [nhn-on7/marketgg-shop#162]
## Overview

1. 변경된 URI 적용
2. 추가 구현된 develop 에 맞춰 권한체크 등 추가 기능 구현

## To-do

- [ ] 관리자, 사용자 권한 체크
- [ ] 관리자의 답변에 따라 문의 상태 변경 기능
- [ ] 변경된 URI 적용
