### ISSUE TITLE
Object Storage 연동

### ISSUE THREAD

**Issue by Com-Sun** [nhn-on7/marketgg-shop#183]
## Overview

1. 서버 구축
2. 서버 연동

## To-do

- [x] Storage container 생성
- [x] 토큰 발급 및 API 테스트
- [x] 오브젝트 업로드
- [x] shop 서버와 서비스 연동
- [x] client 서버와 서비스 연동
