### ISSUE TITLE
상품 문의 Refactoring

### ISSUE THREAD

**Issue by coalong** [nhn-on7/marketgg-shop#231]
## Overview

1. 상품문의 Refactoring

## To-do

- [ ] 상품문의 toDto, toEntity 사용자 정의 mapper 으로 코드 수정
- [ ] 상품문의 공통 객체 반환 코드 수정
- [ ] 상품문의 API Swagger 작성
