### ISSUE TITLE
쿠폰 관리 Refactoring

### ISSUE THREAD

**Issue by coalong** [nhn-on7/marketgg-shop#232]
## Overview

1. 쿠폰 관리 Refactoring

## To-do

- [ ] 쿠폰관리 toDto, toEntity 사용자 정의 mapper 으로 코드 수정
- [ ] 쿠폰관리 공통 객체 반환 코드 수정
- [ ] 쿠폰관리 API Swagger 작성
