### ISSUE TITLE
찜, 후기 리팩토링

### ISSUE THREAD

**Issue by Jungmin-Kim228** [nhn-on7/marketgg-shop#278]
## Overview

1. 찜, 후기 리팩토링

## To-do

- [ ] 이미지 byte -> string 주소로 변경
- [ ] 상품상세 찜 여부(boolean)
- [ ] 상품상세 후기 리스트 추가(페이지 단위로 잘라서)
