### ISSUE TITLE
9.5 시연 피드백

### ISSUE THREAD

**Issue by Jungmin-Kim228** [nhn-on7/marketgg-shop#295]
## Overview

1. 시연 후 피드백 적용

## To-do

- [x] 주문 목록 역순 조회
- [x] 결제 대기 상태 관리자만 조회 가능
- [x] 주문 상세 조회 회원명 추가
- [x] 주문 서비스 테스트 수정
- [ ]  totalOrigin, totalAmount 검증 추가
- [x] 이 외 수정사항 있으면 수정
