### ISSUE TITLE
적립 관리

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-shop#96]
## Overview

1. 회원은 결제 시 회원의 등급에 따라 적립금을 받을 수 있다.
2. 회원은 회원 가입 시 추천인 입력 시 적립금을 받을 수 있다.
3. 회원은 후기 작성 시 후기 종류에 따라 적립금을 받을 수 있다.
4. 회원은 결제 시 회원이 가진 적립금을 사용할 수 있다.

## To-do

- [x] 등급에 따른 적립금 지급
- [x] 추천인 입력 시 적립금 지급
- [x] 후기 작성 시 적립금 지급
- [x] 결제 시 적립금 사용
