### ISSUE TITLE
쿠폰 관리

### ISSUE THREAD

**Issue by Jungmin-Kim228** [nhn-on7/marketgg-shop#97]
## Overview

1. 쿠폰 CRUD, 자동 지급+소멸, MY GG 에서 회원의 쿠폰 조회+등록 기능 구현
2. 쿠폰 Controller, Service TC 작성

## To-do

- [x] 쿠폰 등록
- [x] 쿠폰 조회
- [x] 쿠폰 수정
- [x] 쿠폰 삭제
- [x] Controller TC
- [x] Service TC
- [x] JavaDoc 작성
- [ ] 쿠폰 자동 지급
- [ ] 쿠폰 자동 소멸
- [x] MY GG 회원의 쿠폰 조회
- [x] MY GG 회원의 쿠폰 등록
